version: '3'
services:
  jekyll:
    image: jekyll/jekyll:latest
    volumes:
      - .:/srv/jekyll
      - .:/srv/jekyll:cached,delegated
    ports:
      - "4000:4000"
    command: jekyll serve --host 0.0.0.0
